name: Push to RedGuides
on:
  push:
    tags: [ "v*" ]
  workflow_dispatch: {}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build release.zip
        run: |
          test -d Lua/Arrow || (echo "Expected Lua/Arrow/ in repo" && exit 1)
          zip -r release.zip Lua/Arrow README.md
      - name: Push to RedGuides
        uses: RedGuides/redguides-publish@v1
        env:
          REDGUIDES_API_KEY: ${{ secrets.REDGUIDES_API_KEY }}
        with:
          resource_id: 'YOUR_RESOURCE_ID'
          description: 'README.md'
          file: 'release.zip'
          domain: 'https://raw.githubusercontent.com/Psymorph/arrow/main//Psymorph/arrow/main'
